/*       AND --- &               
         OR  --- |
         NOT --- ~
         XOR --- ^        
 && YEH DO CONITIONS KO EK SAATH EXECUTE KAR SAKTA H          */

#include<iostream>
using namespace std;
int main(){

    int a = 5;
    int b = 8;

    cout<< " a&b " << (a&b) << endl;         // use brackets
    cout<< " a|b " << (a|b) << endl;
    cout<< " ~a " << ~a << endl;
    cout<< " a^b " << (a^b) << endl;
}        